### PR TITLE
Go for simple solution

### PR DESCRIPTION
**Pull request by MokumJ**
- Go for the proposed solution in PR
- Don't use context for mediaqueries.

Checked for an alternative hook/create a hook myself. But we always need a window property to say something about the screen width. So we can't do better than the use-media package. So I suggets to keep using it for now.

With this solution everything works fine

### CODE REVIEW

**Comment by timvanoostrom** [comment]
A solution for use would be to use the solution proposed here: https://github.com/streamich/use-media/issues/26 You'd have to pull the source code in our own codebase though.

**Review by timvanoostrom — APPROVED** [review]

**Comment by MokumJ** [comment]
@timvanoostrom You would still return false if nog window prop available if I understand it correctly.

**Comment by timvanoostrom** [comment]
In browser context the window prop is always available. This app is not universal so SSR isn't a use-case.

**Comment by timvanoostrom** [comment]
Awesome, maybe give some credits to the author of the hook by referencing the GH repo?

**Pull request merged**
