### PR TITLE
update template

### PR DESCRIPTION
**Pull request by MokumJ**

### CODE REVIEW

**Comment by timvanoostrom** [comment]
Do the browsers calculate the hash automatically?

**Comment by MokumJ** [comment]
@timvanoostrom 

Yes so as long as the script stays the same this will work.

https://www.troyhunt.com/locking-down-your-website-scripts-with-csp-hashes-nonces-and-report-uri/

I think a nonce would also work for scripts that we are defining, however for the buurt problem where the script is not hosted on our code base it would be more diffecult.

**Comment by timvanoostrom** [comment]
Nonce is for dynamic inline scripts, not for static scripts like ours.

**Review by timvanoostrom — APPROVED** [review]

**Comment by timvanoostrom** [comment]
Can we close this @MokumJ ?

**Pull request closed without merging**
